version: "3"
services:
  web:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
#      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d

  application:
    container_name: spring-web-ide
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"






#networks:
#  dev-network:

